version: 0.2

phases:
  pre_build:
    commands:
      - terraform -version
      - terraform init
  build:
    commands:
      - terraform plan -out=plan.out

artifacts:
  files:
    - plan.out

cache:
  paths:
    - '.terraform/**/*'
