version: 0.2

env:
  parameter-store:
    TF_VAR_terraform_cloud_token: "TERRAFORM_TOKEN"
  variables:
    SCRIPT_DIR: "./templates/scripts"
    TF_VERSION: "1.6.6"

phases:
  pre_build:
    commands:
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /bin
      - rm terraform.zip
      - echo "credentials \"app.terraform.io\" { token = \"$TF_VAR_terraform_cloud_token\" }" > ~/.terraformrc

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/env/${ENVIRONMENT}
      - mkdir -p ${CODEBUILD_SRC_DIR}/reports
      - "echo ## TERRAFORM PLAN : Generate the Terraform Plan"
      - /bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/plan.sh

artifacts:
  files:
    - '**/*'
